version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  deploy_lambda:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Create Lambda ZIP
          command: |
            # Lambda用のコードをZIP圧縮
            zip -r lambda.zip .  # カレントディレクトリ（Lambda関数のコード）をZIP圧縮

      - run:
          name: Deploy Lambda function
          command: |
            # AWS CLIをインストール
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            # AWS認証情報を環境変数から設定（Contextから引き出される）
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

            # Lambdaのデプロイを実行
            aws lambda update-function-code \
              --function-name YOUR_LAMBDA_FUNCTION_NAME \
              --zip-file fileb://lambda.zip

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_lambda:
          context:
            - aws-credentials
